global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'chat-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080'] # Use Docker service name
  - job_name: 'kafka-broker'
    static_configs:
      - targets: ['kafka:9092']