server:
  forward-headers-strategy: NATIVE
  use-forward-headers: true
spring:
  # Datasource config
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=require
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  # Redis config
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    ssl: true
  # Kafka config
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      properties:
        "allow.auto.create.topics": true
    producer:
      properties:
        "auto.create.topics.enable": true

  jpa:
    hibernate:
      ddl-auto: validate

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS}