spring:
  # --- Datasource config for Koyeb DB ---
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=require
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  # --- Redis config for Upstash ---
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    ssl: true # Upstash requires SSL
  # --- Kafka config for Koyeb/Redpanda ---
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      properties:
        "allow.auto.create.topics": true
    producer:
      properties:
        "auto.create.topics.enable": true

  jpa:
    hibernate:
      ddl-auto: validate